### ISSUE TITLE
Undocumented requirement for OPENAI_API_KEY

### ISSUE THREAD

**Issue by robertDouglass** [AI-ANK/PaLM-Kosmos-Vision#2]
```
...
File "/Users/robert/Code/PaLM-Kosmos-Vision/env/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 340, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
File "/Users/robert/Code/PaLM-Kosmos-Vision/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
...
File "/Users/robert/Code/PaLM-Kosmos-Vision/env/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 161, in get_embeddings
    data = client.embeddings.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...

```

**Comment by AI-ANK** [comment]
Thanks for raising this issue. It's important to note that the OPENAI_API_KEY is not a requirement for running the PaLM-Kosmos-Vision project, as evidenced by our live version [here](https://huggingface.co/spaces/AI-ANK/PaLM-Kosmos-Vision).

The error you're encountering suggests that the service_context and llm are not correctly set in LlamaIndex, which by default assumes OpenAI LLM unless specified otherwise. This could happen if there were changes in the default code.

To resolve this, please ensure that you specify the LLM you intend to use in your implementation. For more details on how to correctly implement LlamaIndex, please refer to their [documentation](https://docs.llamaindex.ai/en/stable/).

Closing this issue as it seems to stem from a code modification on your end.

**Comment by robertDouglass** [comment]
I didn't alter the code at all.

**Comment by AI-ANK** [comment]
Upon further investigation I found that this issue is occurring when using latest version of llamaindex. 0.9 version onwards they changed how default embedding models is set.

so in create_chat_engine function, we need to change:
-     service_context = ServiceContext.from_defaults(llm=llm)
to
-     service_context = ServiceContext.from_defaults(llm=llm, embed_model="local")
This should fix the issue
